name: flutter_floor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.1.0
  floor_generator: ^1.1.0
  floor_annotation: ^1.2.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi_web: ^0.1.0
  path: ^1.8.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
